language: node_js

node_js:
  - "7"

before_script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: "dist"
  on:
    branch: master

notifications:
  email: false
